houshold=read.table(file="household_power_consumption.txt", header=TRUE, sep=";", as.is=TRUE, na.strings="?", colClasses=c("character", "character", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))
wantedData=subset(houshold, Date=="1/2/2007"| Date=="2/2/2007")
wantedData$DateTime=paste(wantedData$Date, wantedData$Time)
wantedData$DateTime=strptime(wantedData$DateTime, "%d/%m/%Y %H:%M:%S")
plot(wantedData$DateTime, wantedData$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
lines(wantedData$DateTime, wantedData$Sub_metering_2, col="red")
lines(wantedData$DateTime, wantedData$Sub_metering_3, col="blue")
legend("topright", col=c("black", "blue", "red"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd=1)
dev.copy(png, file="plot3.png")
dev.off()